Changes (S3)
NCATComp410/comp410_summer21 pull request #32
Opened 2021-07-14 01:09 UTC by pamichals

2021-07-14 12:07 UTC, claesmk requested changes
It looks like you have removed all of the other code and replaced it with yours.  You need to merge your specific handler code into upstream, not replace it

2021-07-14 17:24 UTC, pamichals commented
I added all of the removed code and pushed back to the origin. Sorry!

2021-07-14 22:56 UTC, claesmk commented on log_parse.py
> +        elif id == 114009:
Here is an example of where it looks like you have merged your branch incorrectly with upstream.  I'm not entirely sure how this happened.  If you look at [this](https://github.com/NCATComp410/comp410_summer21/blob/4ab66d1e8c16adf13a5e2dd5394e33875f08e665/log_parse.py#L23) line of code, you'll see how it should look.  You shouldn't be removing the if m: clause and the following line

2021-07-14 22:58 UTC, claesmk commented
It looks like your merge is still incorrect for some reason.  Maybe you made a mistake when resolving conflicts?  Which tool did you use for that? I have inserted an example of the incorrect merge above in a review comment format

2021-07-15 00:18 UTC, pamichals commented
I have a Mac, so I'm using TextEdit (default program) to make my edits. I added the if m portion back and now I just have an AssertionError on my specific portion of the assignment

<img width="597" alt="Screen Shot 2021-07-14 at 8 18 03 PM" src="https://user-images.githubusercontent.com/59964219/125708865-c3fd7f58-aece-4e29-aa62-b73d9edca753.png">

2021-07-15 03:03 UTC, claesmk commented
if you look at your assigned message in [syslogs.txt ](https://github.com/NCATComp410/comp410_summer21/blob/4ab66d1e8c16adf13a5e2dd5394e33875f08e665/syslogs.txt#L261) - your message string does not match the one you currently have in your unit-test.  The correct one is 
```
        self.assertTrue(self.df.loc[114009, 'Text'] == 'Failed to set multicast address in 4GE SSM I/O card (error error_string).')
```

So the message string doesn't match which causes the assertion to fail.  If you correct the message is should work OK

2021-07-15 03:10 UTC, pamichals commented
Thank you for the help! Adding a teammate for review shortly

Have a great night!

2021-07-15 12:16 UTC, claesmk approved these changes
I'll add my review as well.  You can go ahead and merge your pull request.

2021-07-15 13:31 UTC, merged